using NUnit.Framework;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Localization;
[System.Serializable]
public class DialogueLineData 
{
    public string dialogueID;
    public string dialogueSpeaker;
    public LocalizedString dialogueText;
    public string dialogueImage;
    public string dialogueContinue;
    public string nextID;
    public LocalizedString[] resposeOptions;
    public string branchID;
}

//these are generated by the DialogueBase based on the CSV 
